server:
  port: 8090
  servlet:
    context-path: /0.1/
spring:
  application:
    name: portal-bancario
    version: develop
  datasource:
    url: jdbc:mariadb://localhost:3306/dbPortalBancario
    username: jhd
    password: 123456
    driver-class-name: org.mariadb.jdbc.Driver
